# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "web" do |web|
    web.vm.box="debian-base"
    web.vm.hostname = "web.do1.lab"
    web.vm.network "private_network", ip: "192.168.89.100"
    web.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
    web.vm.provision "shell", path: "web.sh"
    web.vm.provider "virtualbox" do |vb|
      vb.name = "WEB"
    end
  end

  config.vm.define "db" do |db|
    db.vm.box="debian-base"
    db.vm.hostname = "db.do1.lab"
    db.vm.network "private_network", ip: "192.168.89.101"
    db.vm.provision "shell", path: "db.sh"
    db.vm.provider "virtualbox" do |vb|
      vb.name = "DB"
    end
  end

end
