# -*- mode: ruby -*-
# vi: set ft=ruby :

$add_hosts = <<-SCRIPT
echo "* Add hosts ..."
echo "192.168.99.100 docker.do1.lab docker" >> /etc/hosts
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "shekeriev/debian-12.11"
  config.vm.hostname = "docker.do1.lab"
  config.vm.network "private_network", ip: "192.168.99.200"
  config.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true
  config.vm.network "forwarded_port", guest: 9000, host: 9000, auto_correct: true
  config.vm.network "forwarded_port", guest: 9443, host: 9443, auto_correct: true

  config.vm.provision :shell, :inline => $add_hosts

  config.vm.provision :shell, path: "docker-setup.sh"

  config.vm.provision :shell, path: "docker-tools.sh"

  config.vm.provider :virtualbox do |vb|
   vb.customize ["modifyvm", :id, "--memory", "2048"]
  end
end
